name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*

  build_macos:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*
